/*
 * Lorie Wayland Compositor — Build System Tests (PR #1)
 *
 * TDD cycle:
 *   RED  : These includes failed because wayland.cmake and
 *          wayland-protocols.cmake did not exist.
 *   GREEN: Recipes now generate the headers and libraries;
 *          these tests compile and pass.
 */

#include "lorie_test.h"

/* Generated by wayland.cmake */
#include "wayland-version.h"
#include "wayland-config.h"

/* Generated by wayland-protocols.cmake */
#include "stable-xdg-shell-xdg-shell.h"
#include "stable-viewporter-viewporter.h"
#include "stable-presentation-time-presentation-time.h"
#include "stable-linux-dmabuf-linux-dmabuf-v1.h"

static void test_wayland_version_header_parsable(void) {
    ASSERT_TRUE(WAYLAND_VERSION_MAJOR >= 1);
    ASSERT_TRUE(WAYLAND_VERSION_MINOR >= 0);
    ASSERT_TRUE(WAYLAND_VERSION_MICRO >= 0);
    ASSERT_NOT_NULL(WAYLAND_VERSION);
    ASSERT_TRUE(WAYLAND_VERSION[0] != '\0');
}

static void test_wayland_config_header_exists(void) {
    ASSERT_EQ_STR("wayland", PACKAGE);
    ASSERT_NOT_NULL(PACKAGE_VERSION);
    ASSERT_TRUE(PACKAGE_VERSION[0] != '\0');
}

static void test_protocol_xdg_shell_header_generated(void) {
    /* Header compiled => scanner ran. Interface name must be non-null. */
    ASSERT_NOT_NULL(xdg_wm_base_interface.name);
}

static void test_protocol_viewporter_header_generated(void) {
    ASSERT_NOT_NULL(wp_viewporter_interface.name);
}

static void test_protocol_presentation_time_header_generated(void) {
    ASSERT_NOT_NULL(wp_presentation_interface.name);
}

static void test_protocol_linux_dmabuf_header_generated(void) {
    ASSERT_NOT_NULL(zwp_linux_dmabuf_v1_interface.name);
}

int lorie_test_build_suite(struct lorie_test_suite* suite) {
    lorie_suite_init(suite, "build", NULL, NULL);
    SUITE_ADD(suite, test_wayland_version_header_parsable);
    SUITE_ADD(suite, test_wayland_config_header_exists);
    SUITE_ADD(suite, test_protocol_xdg_shell_header_generated);
    SUITE_ADD(suite, test_protocol_viewporter_header_generated);
    SUITE_ADD(suite, test_protocol_presentation_time_header_generated);
    SUITE_ADD(suite, test_protocol_linux_dmabuf_header_generated);
    return 0;
}
