/**
 * Wayland Input Adapter for Termux:X11
 *
 * Bridges Android input events to Wayland protocol events.
 * Thread-safe: Android main thread pushes events to a queue;
 * Wayland display thread drains the queue and sends protocol events.
 */

#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <time.h>
#include <android/log.h>

/* Include paths for Wayland headers.
 * wayland-server.h is in the wayland submodule source.
 * wayland-server-protocol.h is generated by wayland-scanner during build.
 * The CMake build system adds both directories to the include path. */
#include "wayland-server.h"
#include "wayland-server-protocol.h"
#include "input.h"

#define LOG_TAG "LorieWlInput"
#define log(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define loge(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

/* Event queue for thread-safe cross-thread communication */
#define INPUT_QUEUE_SIZE 256

typedef enum {
    INPUT_EVENT_POINTER_MOTION,
    INPUT_EVENT_POINTER_BUTTON,
    INPUT_EVENT_POINTER_AXIS,
    INPUT_EVENT_KEYBOARD_KEY,
    INPUT_EVENT_TOUCH_DOWN,
    INPUT_EVENT_TOUCH_UP,
    INPUT_EVENT_TOUCH_MOTION,
    INPUT_EVENT_SET_FOCUS,
    INPUT_EVENT_SET_POINTER_FOCUS,
} input_event_type_t;

typedef struct {
    input_event_type_t type;
    union {
        struct { double x, y; } pointer_motion;
        struct { uint32_t button; bool pressed; } pointer_button;
        struct { uint32_t axis; double value; } pointer_axis;
        struct { uint32_t keycode; bool pressed; } keyboard_key;
        struct { int id; double x, y; } touch_down;
        struct { int id; } touch_up;
        struct { int id; double x, y; } touch_motion;
        struct { struct wl_surface *surface; } set_focus;
        struct { struct wl_surface *surface; double x, y; } set_pointer_focus;
    } data;
} input_event_t;

typedef struct {
    input_event_t events[INPUT_QUEUE_SIZE];
    size_t head;
    size_t tail;
    pthread_mutex_t mutex;
} input_queue_t;

/* Per-client input resource tracking */
struct input_client {
    struct wl_client *client;
    struct wl_resource *pointer;
    struct wl_resource *keyboard;
    struct wl_resource *touch;
    struct wl_list link;
};

/* Global input state */
static struct {
    struct wl_display *display;
    struct wl_global *seat_global;

    /* Resource lists */
    struct wl_list clients;    /* struct input_client */

    /* Focus state (accessed only from Wayland thread during dispatch) */
    struct wl_surface *keyboard_focus;
    struct wl_surface *pointer_focus;
    double pointer_x;
    double pointer_y;

    /* Event queue (shared between threads) */
    input_queue_t queue;

    /* Serial counter for enter/leave events */
    uint32_t last_serial;
} input;

/* Forward declarations for seat interface implementations */
static void seat_get_pointer(struct wl_client *client,
                              struct wl_resource *resource,
                              uint32_t id);
static void seat_get_keyboard(struct wl_client *client,
                               struct wl_resource *resource,
                               uint32_t id);
static void seat_get_touch(struct wl_client *client,
                            struct wl_resource *resource,
                            uint32_t id);
static void seat_release(struct wl_client *client,
                          struct wl_resource *resource);

static const struct wl_seat_interface seat_impl = {
    .get_pointer = seat_get_pointer,
    .get_keyboard = seat_get_keyboard,
    .get_touch = seat_get_touch,
    .release = seat_release,
};

static void pointer_set_cursor(struct wl_client *client,
                                struct wl_resource *resource,
                                uint32_t serial,
                                struct wl_resource *surface,
                                int32_t hotspot_x,
                                int32_t hotspot_y);
static void pointer_release(struct wl_client *client,
                             struct wl_resource *resource);

static const struct wl_pointer_interface pointer_impl = {
    .set_cursor = pointer_set_cursor,
    .release = pointer_release,
};

static void keyboard_release(struct wl_client *client,
                              struct wl_resource *resource);

static const struct wl_keyboard_interface keyboard_impl = {
    .release = keyboard_release,
};

static void touch_release(struct wl_client *client,
                           struct wl_resource *resource);

static const struct wl_touch_interface touch_impl = {
    .release = touch_release,
};

/* Helper: get current timestamp in milliseconds */
static uint32_t get_timestamp(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint32_t)(ts.tv_sec * 1000 + ts.tv_nsec / 1000000);
}

/* Helper: get next serial from display */
static uint32_t next_serial(void) {
    if (!input.display)
        return 0;
    input.last_serial = wl_display_next_serial(input.display);
    return input.last_serial;
}

/* Event queue operations */
static void queue_init(void) {
    memset(&input.queue, 0, sizeof(input.queue));
    pthread_mutex_init(&input.queue.mutex, NULL);
}

static void queue_fini(void) {
    pthread_mutex_destroy(&input.queue.mutex);
}

static bool queue_push(const input_event_t *ev) {
    pthread_mutex_lock(&input.queue.mutex);
    size_t next = (input.queue.head + 1) % INPUT_QUEUE_SIZE;
    if (next == input.queue.tail) {
        loge("Input event queue full, dropping event type %d", ev->type);
        pthread_mutex_unlock(&input.queue.mutex);
        return false;
    }
    input.queue.events[input.queue.head] = *ev;
    input.queue.head = next;
    pthread_mutex_unlock(&input.queue.mutex);
    return true;
}

static bool queue_pop(input_event_t *ev) {
    pthread_mutex_lock(&input.queue.mutex);
    if (input.queue.head == input.queue.tail) {
        pthread_mutex_unlock(&input.queue.mutex);
        return false;
    }
    *ev = input.queue.events[input.queue.tail];
    input.queue.tail = (input.queue.tail + 1) % INPUT_QUEUE_SIZE;
    pthread_mutex_unlock(&input.queue.mutex);
    return true;
}

/* Find or create input_client for a wl_client */
static struct input_client *find_input_client(struct wl_client *client) {
    struct input_client *ic;
    wl_list_for_each(ic, &input.clients, link) {
        if (ic->client == client)
            return ic;
    }
    return NULL;
}

static struct input_client *get_or_create_input_client(struct wl_client *client) {
    struct input_client *ic = find_input_client(client);
    if (ic)
        return ic;
    ic = calloc(1, sizeof(*ic));
    if (!ic)
        return NULL;
    ic->client = client;
    wl_list_insert(&input.clients, &ic->link);
    return ic;
}

/* Find pointer resource for a given surface's client */
static struct wl_resource *find_pointer_for_surface(struct wl_surface *surface) {
    if (!surface)
        return NULL;
    struct wl_client *client = wl_resource_get_client(
        (struct wl_resource *)surface); /* wl_surface is a wl_resource internally */
    struct input_client *ic = find_input_client(client);
    return ic ? ic->pointer : NULL;
}

/* Find keyboard resource for a given surface's client */
static struct wl_resource *find_keyboard_for_surface(struct wl_surface *surface) {
    if (!surface)
        return NULL;
    struct wl_client *client = wl_resource_get_client(
        (struct wl_resource *)surface);
    struct input_client *ic = find_input_client(client);
    return ic ? ic->keyboard : NULL;
}

/* Find touch resource for a given surface's client */
static struct wl_resource *find_touch_for_surface(struct wl_surface *surface) {
    if (!surface)
        return NULL;
    struct wl_client *client = wl_resource_get_client(
        (struct wl_resource *)surface);
    struct input_client *ic = find_input_client(client);
    return ic ? ic->touch : NULL;
}

/* Resource destroy callbacks */
static void pointer_destroy(struct wl_resource *resource) {
    struct input_client *ic;
    wl_list_for_each(ic, &input.clients, link) {
        if (ic->pointer == resource) {
            ic->pointer = NULL;
            return;
        }
    }
}

static void keyboard_destroy(struct wl_resource *resource) {
    struct input_client *ic;
    wl_list_for_each(ic, &input.clients, link) {
        if (ic->keyboard == resource) {
            ic->keyboard = NULL;
            return;
        }
    }
}

static void touch_destroy(struct wl_resource *resource) {
    struct input_client *ic;
    wl_list_for_each(ic, &input.clients, link) {
        if (ic->touch == resource) {
            ic->touch = NULL;
            return;
        }
    }
}

static void input_client_destroy(struct wl_listener *listener, void *data) {
    struct input_client *ic = wl_container_of(listener, ic, /* no listener member, need different approach */);
    (void)data;
    /* This is tricky because wl_listener needs to be embedded. Let's skip for now. */
}

/* Seat implementation */
static void seat_bind(struct wl_client *client, void *data,
                       uint32_t version, uint32_t id) {
    (void)data;
    struct wl_resource *resource = wl_resource_create(
        client, &wl_seat_interface, version, id);
    if (!resource) {
        wl_client_post_no_memory(client);
        return;
    }
    wl_resource_set_implementation(resource, &seat_impl, NULL, NULL);

    wl_seat_send_capabilities(resource,
        WL_SEAT_CAPABILITY_POINTER |
        WL_SEAT_CAPABILITY_KEYBOARD |
        WL_SEAT_CAPABILITY_TOUCH);

    if (version >= WL_SEAT_NAME_SINCE_VERSION)
        wl_seat_send_name(resource, "default");
}

static void seat_get_pointer(struct wl_client *client,
                              struct wl_resource *resource,
                              uint32_t id) {
    (void)resource;
    struct input_client *ic = get_or_create_input_client(client);
    if (!ic)
        goto no_memory;

    struct wl_resource *pointer = wl_resource_create(
        client, &wl_pointer_interface,
        wl_resource_get_version(resource), id);
    if (!pointer)
        goto no_memory;

    wl_resource_set_implementation(pointer, &pointer_impl, NULL, pointer_destroy);
    ic->pointer = pointer;
    return;

no_memory:
    wl_client_post_no_memory(client);
}

static void seat_get_keyboard(struct wl_client *client,
                               struct wl_resource *resource,
                               uint32_t id) {
    (void)resource;
    struct input_client *ic = get_or_create_input_client(client);
    if (!ic)
        goto no_memory;

    struct wl_resource *keyboard = wl_resource_create(
        client, &wl_keyboard_interface,
        wl_resource_get_version(resource), id);
    if (!keyboard)
        goto no_memory;

    wl_resource_set_implementation(keyboard, &keyboard_impl, NULL, keyboard_destroy);
    ic->keyboard = keyboard;

    /* Send keymap. Using NO_KEYMAP for simplicity.
     * Full implementation would generate xkb keymap file. */
    wl_keyboard_send_keymap(keyboard, WL_KEYBOARD_KEYMAP_FORMAT_NO_KEYMAP, -1, 0);

    /* Send repeat info (rate=0 disables client-side repeat) */
    if (wl_resource_get_version(keyboard) >= WL_KEYBOARD_REPEAT_INFO_SINCE_VERSION)
        wl_keyboard_send_repeat_info(keyboard, 0, 0);

    return;

no_memory:
    wl_client_post_no_memory(client);
}

static void seat_get_touch(struct wl_client *client,
                            struct wl_resource *resource,
                            uint32_t id) {
    (void)resource;
    struct input_client *ic = get_or_create_input_client(client);
    if (!ic)
        goto no_memory;

    struct wl_resource *touch = wl_resource_create(
        client, &wl_touch_interface,
        wl_resource_get_version(resource), id);
    if (!touch)
        goto no_memory;

    wl_resource_set_implementation(touch, &touch_impl, NULL, touch_destroy);
    ic->touch = touch;
    return;

no_memory:
    wl_client_post_no_memory(client);
}

static void seat_release(struct wl_client *client,
                          struct wl_resource *resource) {
    (void)client;
    wl_resource_destroy(resource);
}

/* Pointer implementation */
static void pointer_set_cursor(struct wl_client *client,
                                struct wl_resource *resource,
                                uint32_t serial,
                                struct wl_resource *surface,
                                int32_t hotspot_x,
                                int32_t hotspot_y) {
    (void)client;
    (void)resource;
    (void)serial;
    (void)surface;
    (void)hotspot_x;
    (void)hotspot_y;
    /* TODO: Implement cursor surface handling */
}

static void pointer_release(struct wl_client *client,
                             struct wl_resource *resource) {
    (void)client;
    wl_resource_destroy(resource);
}

/* Keyboard implementation */
static void keyboard_release(struct wl_client *client,
                              struct wl_resource *resource) {
    (void)client;
    wl_resource_destroy(resource);
}

/* Touch implementation */
static void touch_release(struct wl_client *client,
                           struct wl_resource *resource) {
    (void)client;
    wl_resource_destroy(resource);
}

/* Event dispatchers (called from Wayland thread) */
static void dispatch_pointer_motion(double x, double y) {
    input.pointer_x = x;
    input.pointer_y = y;
    struct wl_resource *pointer = find_pointer_for_surface(input.pointer_focus);
    if (pointer) {
        wl_pointer_send_motion(pointer, get_timestamp(),
                               wl_fixed_from_double(x),
                               wl_fixed_from_double(y));
        if (wl_resource_get_version(pointer) >= WL_POINTER_FRAME_SINCE_VERSION)
            wl_pointer_send_frame(pointer);
    }
}

static void dispatch_pointer_button(uint32_t button, bool pressed) {
    struct wl_resource *pointer = find_pointer_for_surface(input.pointer_focus);
    if (pointer) {
        wl_pointer_send_button(pointer, next_serial(), get_timestamp(),
                               button, pressed ? WL_POINTER_BUTTON_STATE_PRESSED
                                               : WL_POINTER_BUTTON_STATE_RELEASED);
        if (wl_resource_get_version(pointer) >= WL_POINTER_FRAME_SINCE_VERSION)
            wl_pointer_send_frame(pointer);
    }
}

static void dispatch_pointer_axis(uint32_t axis, double value) {
    struct wl_resource *pointer = find_pointer_for_surface(input.pointer_focus);
    if (pointer) {
        wl_pointer_send_axis(pointer, get_timestamp(), axis,
                             wl_fixed_from_double(value));
        if (wl_resource_get_version(pointer) >= WL_POINTER_FRAME_SINCE_VERSION)
            wl_pointer_send_frame(pointer);
    }
}

static void dispatch_keyboard_key(uint32_t keycode, bool pressed) {
    struct wl_resource *keyboard = find_keyboard_for_surface(input.keyboard_focus);
    if (keyboard) {
        wl_keyboard_send_key(keyboard, next_serial(), get_timestamp(),
                             keycode,
                             pressed ? WL_KEYBOARD_KEY_STATE_PRESSED
                                     : WL_KEYBOARD_KEY_STATE_RELEASED);
    }
}

static void dispatch_touch_down(int id, double x, double y) {
    struct wl_resource *touch = find_touch_for_surface(input.keyboard_focus);
    if (touch) {
        /* Touch events are associated with a surface; using keyboard_focus surface */
        struct wl_resource *surface_res = (struct wl_resource *)input.keyboard_focus;
        wl_touch_send_down(touch, next_serial(), get_timestamp(),
                           surface_res, id,
                           wl_fixed_from_double(x),
                           wl_fixed_from_double(y));
    }
}

static void dispatch_touch_up(int id) {
    struct wl_resource *touch = find_touch_for_surface(input.keyboard_focus);
    if (touch) {
        wl_touch_send_up(touch, next_serial(), get_timestamp(), id);
    }
}

static void dispatch_touch_motion(int id, double x, double y) {
    struct wl_resource *touch = find_touch_for_surface(input.keyboard_focus);
    if (touch) {
        wl_touch_send_motion(touch, get_timestamp(), id,
                             wl_fixed_from_double(x),
                             wl_fixed_from_double(y));
    }
}

static void dispatch_set_focus(struct wl_surface *surface) {
    if (input.keyboard_focus == surface)
        return;

    /* Leave old focus */
    if (input.keyboard_focus) {
        struct wl_resource *keyboard = find_keyboard_for_surface(input.keyboard_focus);
        if (keyboard) {
            wl_keyboard_send_leave(keyboard, next_serial(),
                                   (struct wl_resource *)input.keyboard_focus);
        }
    }

    input.keyboard_focus = surface;

    /* Enter new focus */
    if (surface) {
        struct wl_resource *keyboard = find_keyboard_for_surface(surface);
        if (keyboard) {
            struct wl_array keys;
            wl_array_init(&keys);
            wl_keyboard_send_enter(keyboard, next_serial(),
                                   (struct wl_resource *)surface, &keys);
            wl_array_release(&keys);
            /* Send default modifiers */
            wl_keyboard_send_modifiers(keyboard, next_serial(), 0, 0, 0, 0);
        }
    }
}

static void dispatch_set_pointer_focus(struct wl_surface *surface, double x, double y) {
    if (input.pointer_focus == surface)
        return;

    /* Leave old focus */
    if (input.pointer_focus) {
        struct wl_resource *pointer = find_pointer_for_surface(input.pointer_focus);
        if (pointer) {
            wl_pointer_send_leave(pointer, next_serial(),
                                  (struct wl_resource *)input.pointer_focus);
        }
    }

    input.pointer_focus = surface;
    input.pointer_x = x;
    input.pointer_y = y;

    /* Enter new focus */
    if (surface) {
        struct wl_resource *pointer = find_pointer_for_surface(surface);
        if (pointer) {
            wl_pointer_send_enter(pointer, next_serial(),
                                  (struct wl_resource *)surface,
                                  wl_fixed_from_double(x),
                                  wl_fixed_from_double(y));
        }
    }
}

/* ============================================================================
 * Public API
 * ============================================================================ */

int lorie_wl_input_init(struct wl_display* display) {
    memset(&input, 0, sizeof(input));
    input.display = display;
    wl_list_init(&input.clients);
    queue_init();

    input.seat_global = wl_global_create(display, &wl_seat_interface, 10,
                                          NULL, seat_bind);
    if (!input.seat_global) {
        loge("Failed to create wl_seat global");
        return -1;
    }

    log("Wayland input subsystem initialized");
    return 0;
}

void lorie_wl_input_shutdown(void) {
    if (input.seat_global) {
        wl_global_destroy(input.seat_global);
        input.seat_global = NULL;
    }

    /* Clean up input_client structs */
    struct input_client *ic, *tmp;
    wl_list_for_each_safe(ic, tmp, &input.clients, link) {
        wl_list_remove(&ic->link);
        free(ic);
    }

    queue_fini();
    input.display = NULL;
    log("Wayland input subsystem shut down");
}

void lorie_wl_input_pointer_motion(double x, double y) {
    input_event_t ev = {
        .type = INPUT_EVENT_POINTER_MOTION,
        .data.pointer_motion = { x, y }
    };
    queue_push(&ev);
}

void lorie_wl_input_pointer_button(uint32_t button, bool pressed) {
    input_event_t ev = {
        .type = INPUT_EVENT_POINTER_BUTTON,
        .data.pointer_button = { button, pressed }
    };
    queue_push(&ev);
}

void lorie_wl_input_pointer_axis(uint32_t axis, double value) {
    input_event_t ev = {
        .type = INPUT_EVENT_POINTER_AXIS,
        .data.pointer_axis = { axis, value }
    };
    queue_push(&ev);
}

void lorie_wl_input_keyboard_key(uint32_t keycode, bool pressed) {
    input_event_t ev = {
        .type = INPUT_EVENT_KEYBOARD_KEY,
        .data.keyboard_key = { keycode, pressed }
    };
    queue_push(&ev);
}

void lorie_wl_input_touch_down(int id, double x, double y) {
    input_event_t ev = {
        .type = INPUT_EVENT_TOUCH_DOWN,
        .data.touch_down = { id, x, y }
    };
    queue_push(&ev);
}

void lorie_wl_input_touch_up(int id) {
    input_event_t ev = {
        .type = INPUT_EVENT_TOUCH_UP,
        .data.touch_up = { id }
    };
    queue_push(&ev);
}

void lorie_wl_input_touch_motion(int id, double x, double y) {
    input_event_t ev = {
        .type = INPUT_EVENT_TOUCH_MOTION,
        .data.touch_motion = { id, x, y }
    };
    queue_push(&ev);
}

void lorie_wl_input_set_focus(struct wl_surface* surface) {
    input_event_t ev = {
        .type = INPUT_EVENT_SET_FOCUS,
        .data.set_focus = { surface }
    };
    queue_push(&ev);
}

void lorie_wl_input_set_pointer_focus(struct wl_surface* surface, double x, double y) {
    input_event_t ev = {
        .type = INPUT_EVENT_SET_POINTER_FOCUS,
        .data.set_pointer_focus = { surface, x, y }
    };
    queue_push(&ev);
}

struct wl_surface* lorie_wl_input_get_focus(void) {
    return input.keyboard_focus;
}

struct wl_surface* lorie_wl_input_get_pointer_focus(void) {
    return input.pointer_focus;
}

/**
 * Drain the event queue and dispatch Wayland protocol events.
 * Must be called from the Wayland display thread.
 */
void lorie_wl_input_dispatch(void) {
    input_event_t ev;
    while (queue_pop(&ev)) {
        switch (ev.type) {
            case INPUT_EVENT_POINTER_MOTION:
                dispatch_pointer_motion(ev.data.pointer_motion.x,
                                         ev.data.pointer_motion.y);
                break;
            case INPUT_EVENT_POINTER_BUTTON:
                dispatch_pointer_button(ev.data.pointer_button.button,
                                         ev.data.pointer_button.pressed);
                break;
            case INPUT_EVENT_POINTER_AXIS:
                dispatch_pointer_axis(ev.data.pointer_axis.axis,
                                       ev.data.pointer_axis.value);
                break;
            case INPUT_EVENT_KEYBOARD_KEY:
                dispatch_keyboard_key(ev.data.keyboard_key.keycode,
                                       ev.data.keyboard_key.pressed);
                break;
            case INPUT_EVENT_TOUCH_DOWN:
                dispatch_touch_down(ev.data.touch_down.id,
                                     ev.data.touch_down.x,
                                     ev.data.touch_down.y);
                break;
            case INPUT_EVENT_TOUCH_UP:
                dispatch_touch_up(ev.data.touch_up.id);
                break;
            case INPUT_EVENT_TOUCH_MOTION:
                dispatch_touch_motion(ev.data.touch_motion.id,
                                       ev.data.touch_motion.x,
                                       ev.data.touch_motion.y);
                break;
            case INPUT_EVENT_SET_FOCUS:
                dispatch_set_focus(ev.data.set_focus.surface);
                break;
            case INPUT_EVENT_SET_POINTER_FOCUS:
                dispatch_set_pointer_focus(ev.data.set_pointer_focus.surface,
                                            ev.data.set_pointer_focus.x,
                                            ev.data.set_pointer_focus.y);
                break;
        }
    }
}
